spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
         github:
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          scope:
           - user:email
           - read:user